# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
