# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sale_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='active',
            new_name='is_active',
        ),
    ]
