# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160713_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='name',
            field=models.CharField(default='ee', max_length=100),
            preserve_default=False,
        ),
    ]
