# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160714_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CommandContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='command',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_content',
            field=models.ManyToManyField(to='app.CartContent'),
        ),
        migrations.AddField(
            model_name='command',
            name='command_content',
            field=models.ManyToManyField(to='app.CommandContent'),
        ),
    ]
